#!/usr/bin/env bash
# This script configures Nginx to add a custom X-Served-By header with the server hostname

apt-get update -y
apt-get install -y nginx

# Add custom header to Nginx config
sed -i '/http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart
