#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin
sudo apt-get update
sudo apt-get -y install haproxy
# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend frontend_cluster
    bind *:80
    default_backend backend_cluster
backend backend_cluster
    balance roundrobin
    server 7002-web-01 44.201.158.142:80 check
    server 7002-web-02 3.85.90.63:80 check
EOF
sudo service haproxy restart
