#!/usr/bin/env bash
# Install nginx and configure it

apt-get update -y
apt-get install -y nginx

# Create the required page
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx (without systemctl)
service nginx restart
