#!/usr/bin/env bash
# Install nginx and configure the default page

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

service nginx restart
