#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301

apt-get update -y
apt-get install -y nginx

sudo sed -i '/server_name _/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
