#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i '/server_name _/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
