#!/usr/bin/env bash
# Configure nginx with a custom 404 page

# Install nginx on a fresh Ubuntu machine
apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Overwrite default nginx site configuration
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Start nginx
service nginx restart
